#region License, Terms and Conditions

//
// IChargifyConfig.cs
//
// Authors: Generated by refactoring assistant
// Copyright (C) 2010 Clinical Support Systems, Inc. All rights reserved.
// 
//  THIS FILE IS LICENSED UNDER THE MIT LICENSE AS OUTLINED IMMEDIATELY BELOW:
//
//  Permission is hereby granted, free of charge, to any person obtaining a
//  copy of this software and associated documentation files (the "Software"),
//  to deal in the Software without restriction, including without limitation
//  the rights to use, copy, modify, merge, publish, distribute, sublicense,
//  and/or sell copies of the Software, and to permit persons to whom the
//  Software is furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in
//  all copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
//  FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
//  DEALINGS IN THE SOFTWARE.
//

#endregion

namespace ChargifyNET.Configuration
{
    /// <summary>
    ///     Abstraction for retrieving Chargify account configuration across full .NET Framework and .NET (Core) targets.
    /// </summary>
    public interface IChargifyConfig
    {
        /// <summary>
        ///     Returns configured default account name
        /// </summary>
        string? DefaultAccount { get; }

        /// <summary>
        ///     Retrieve the default (or first) account configuration.
        /// </summary>
        IChargifyAccountConfig GetDefaultOrFirst();

        /// <summary>
        ///     Retrieve the shared key for the default (or first) account.
        /// </summary>
        string GetSharedKeyForDefaultOrFirstSite();

        /// <summary>
        ///     Returns whether JSON should be used.
        /// </summary>
        bool UseJSON { get; }
    }

    /// <summary>
    ///     Cross-framework abstraction of a single account element.
    /// </summary>
    public interface IChargifyAccountConfig
    {
        /// <summary>
        /// Gets the name associated with the current instance.
        /// </summary>
        string Name { get; }

        /// <summary>
        /// Gets the site URL for the Chargify account. 
        /// </summary>
        string Site { get; }

        /// <summary>
        /// Gets the API key used to authenticate requests to the service.
        /// </summary>
        string ApiKey { get; }

        /// <summary>
        /// Gets the API password used for authenticating requests to the external service.
        /// </summary>
        /// <remarks>The API password should be kept secure and not exposed in client applications or
        /// logs. Access to this property may be restricted depending on the application's security model.</remarks>
        string ApiPassword { get; }

        /// <summary>
        /// Gets the shared secret key used for authentication or encryption.
        /// </summary>
        string SharedKey { get; }

        /// <summary>
        ///    Returns whether CVV is required.
        /// </summary>
        bool CvvRequired { get; }
    }
}
